In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import pandas as pd

data=pd.read_csv("/kaggle/input/insurance/insurance.csv")
data.head(5)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df_encoded = pd.get_dummies(df, columns=['sex', 'smoker', 'region'], drop_first=True)

In [3]:
data=pd.get_dummies(data,columns=['sex','smoker','region'],drop_first=True)

In [5]:
data.head(5)

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False

In [15]:
X=data.drop(['charges'],axis=1)

In [16]:
y=data['charges']

In [17]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=19)

In [21]:
from sklearn.ensemble import RandomForestRegressor

In [23]:
model=RandomForestRegressor()
model.fit(X_train,y_train)
pre=model.predict(X_test)

In [28]:
from sklearn.metrics import r2_score
print("R2 Score:", r2_score(y_test,pre))

R2 Score: 0.8605793664830056

In [31]:
new_data = pd.DataFrame({
    'age': [35],
    'bmi': [28.5],
    'children': [2],
    'sex_male': [1],           # male → 1 (female is dropped column)
    'smoker_yes': [1],         # smoker → yes = 1
    'region_northwest': [0],
    'region_southeast': [1],   # southeast → 1
    'region_southwest': [0]
})

pre=model.predict(new_data)
print(pre)

[23061.6577599]